--1. MARTIN이 속한 부서에서 MARTIN의 급여 이상인 사원수와 부서번호를 출력하라(컬럼명은 사원수 와 부서번호)
SELECT DEPTNO AS 부서번호, COUNT(*) AS 사원수
FROM (
	SELECT D.DEPTNO, ENAME, DNAME, SAL
	FROM EMP E JOIN DEPT D
	ON E.DEPTNO = D.DEPTNO
	WHERE E.DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'MARTIN')
	AND SAL >= (SELECT SAL FROM EMP WHERE ENAME = 'MARTIN')
)
GROUP BY DEPTNO
;

--2. 각 부서의 월급 합계가 8000이 넘는 부서명 오름차순 
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN (
    SELECT D.DEPTNO
    FROM DEPT D LEFT OUTER JOIN EMP E
    ON D.DEPTNO = E.DEPTNO
    GROUP BY D.DEPTNO
    HAVING SUM(SAL) >  9000
)
ORDER BY DNAME;
-- RESEARCH
-- SALES